name = "no-mistakes"
version = "1.60.2"
description = "A local Git proxy that AI-validates your code before push, forwarding only clean commits upstream."
homepage = "https://kunchenguid.github.io/no-mistakes"
license = "MIT"
kind = "app"
bin = ["no-mistakes.exe"]

[source.x64]
url = "https://github.com/kunchenguid/no-mistakes/releases/download/v1.60.2/no-mistakes-v1.60.2-windows-amd64.zip"
sha256 = "9e94d0afe56195ee16d33f3251056e341a8b289cfd6582a180433f055d04e5a1"

[source.arm64]
url = "https://github.com/kunchenguid/no-mistakes/releases/download/v1.60.2/no-mistakes-v1.60.2-windows-arm64.zip"
sha256 = "030cfdaed257920b28810c026d89eb798695c24229e86b907f52df46d2bd0f96"

[env]
NO_MISTAKES_NO_UPDATE_CHECK = "1"

[autoupdate]
checkver = { github = "kunchenguid/no-mistakes" }
url_template = { x64 = "https://github.com/kunchenguid/no-mistakes/releases/download/v$version/no-mistakes-v$version-windows-amd64.zip", arm64 = "https://github.com/kunchenguid/no-mistakes/releases/download/v$version/no-mistakes-v$version-windows-arm64.zip" }
