name = "no-mistakes"
version = "1.64.0"
description = "A local Git proxy that AI-validates your code before push, forwarding only clean commits upstream."
homepage = "https://kunchenguid.github.io/no-mistakes"
license = "MIT"
kind = "app"
bin = ["no-mistakes.exe"]

[source.x64]
url = "https://github.com/kunchenguid/no-mistakes/releases/download/v1.64.0/no-mistakes-v1.64.0-windows-amd64.zip"
sha256 = "6ee7802f31fc1ba992de1fb3ed0a403661b934004d342ac3f93fd102175499c7"

[source.arm64]
url = "https://github.com/kunchenguid/no-mistakes/releases/download/v1.64.0/no-mistakes-v1.64.0-windows-arm64.zip"
sha256 = "bbf312ed5ae3f73c4d4ba6d091c8b1a5fd2eda09d5548494d537a7ec0eb1ed9b"

[env]
NO_MISTAKES_NO_UPDATE_CHECK = "1"

[autoupdate]
checkver = { github = "kunchenguid/no-mistakes" }
url_template = { x64 = "https://github.com/kunchenguid/no-mistakes/releases/download/v$version/no-mistakes-v$version-windows-amd64.zip", arm64 = "https://github.com/kunchenguid/no-mistakes/releases/download/v$version/no-mistakes-v$version-windows-arm64.zip" }
