name = "dn-tool-container"
version = "1.5.1"
description = "Extendable application which can install multiple tools."
homepage = "https://github.com/como65416/DnToolContainer"
license = "MIT"
kind = "app"
extract_dir = "DN-Tool-Container-win32-x64"
shortcuts = [{ target = "DN-Tool-Container.exe", name = "DN Tool Container" }]

[source.x64]
url = "https://github.com/como65416/DnToolContainer/releases/download/1.5.1/DN-Tool-Container-win32-x64.zip"
sha256 = "d347f2627a74f016f7b134afb84f4b628296477685aac4d766e93f61d5961a87"

[autoupdate]
checkver = { github = "como65416/DnToolContainer" }
