name = "zulumc"
version = "9.1.2.47"
description = "A build of JDK Mission Control, an open source Java runtime profiling and monitoring utility"
homepage = "https://www.azul.com/products/components/zulu-mission-control/"
license = "UPL-1.0"
kind = "app"
extract_dir = "zmc9.1.2.47-ca-win_x64\\Azul Mission Control"
bin = ["zmc.exe"]

[source.x64]
url = "https://cdn.azul.com/zmc/bin/zmc9.1.2.47-ca-win_x64.zip"
sha256 = "9ce6d1132c6d93e67c16c474260b50090f799323a6c0366289c9e1e8e7d87194"

[autoupdate]
checkver = "zmc([\\d.]+)-ca-win"
