name = "difftastic"
version = "0.69.0"
description = "A structural diff that understands syntax"
homepage = "https://difftastic.wilfred.me.uk"
license = "MIT"
kind = "app"
bin = ["difft.exe"]

[source.x64]
url = "https://github.com/Wilfred/difftastic/releases/download/0.69.0/difft-x86_64-pc-windows-msvc.zip"
sha256 = "a5adbf57eb1b923b62d1c3596c4f827df143f5b52cfba48bb9e83f41dea90c02"

[source.arm64]
url = "https://github.com/Wilfred/difftastic/releases/download/0.69.0/difft-aarch64-pc-windows-msvc.zip"
sha256 = "fa709e803088b54774adf0111409483ee5edfbbc1f9dcc5610e81e4ed3841e53"

[autoupdate]
checkver = { github = "Wilfred/difftastic" }
url_template = { x64 = "https://github.com/Wilfred/difftastic/releases/download/$version/difft-x86_64-pc-windows-msvc.zip", arm64 = "https://github.com/Wilfred/difftastic/releases/download/$version/difft-aarch64-pc-windows-msvc.zip" }
