name = "intellij-jbr21-sdk-jcef"
version = "21.0.11-b1163.116"
description = "A fork of OpenJDK that includes a number enhancements in font rendering, HiDPI support, ligatures, performance improvements, and bugfixes. These are mainly for running IntelliJ Platform-based products"
homepage = "https://github.com/JetBrains/JetBrainsRuntime"
license = "GPL-2.0"
kind = "app"

[source.x64]
url = "https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-21.0.11-windows-x64-b1163.116.tar.gz"
sha512 = "0968d381735d502dcf2f5b21980f6be1447739721441a191226a75b2a4c6f4a01dca9d2187a49e66d92e1107744c7a5a1d4ec8ff1c7730b55ed228618975ee2a"
extract_dir = "jbrsdk_jcef-21.0.11-windows-x64-b1163.116"

[source.arm64]
url = "https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-21.0.11-windows-aarch64-b1163.116.tar.gz"
sha512 = "071e92e726af89bde7fb8508f3366d6d330f5a56f9e5d4babf3ba0fdf8ae309b59ced3c50abc3f79a8250c833f3c5ea435eee5f2c18152e313af3348797e098f"
extract_dir = "jbrsdk_jcef-21.0.11-windows-aarch64-b1163.116"

[env]
JAVA_HOME = "{dir}"
PATH = "{dir}\\bin"

[autoupdate]
checkver = { github = "JetBrains/JetBrainsRuntime" }
