name = "gtoolkit"
version = "1.1.529"
description = "A moldable development environment."
homepage = "https://gtoolkit.com"
license = "MIT"
kind = "app"
bin = ["bin\\GlamorousToolkit-cli.exe"]
shortcuts = [{ target = "bin\\GlamorousToolkit.exe", name = "GlamorousToolkit" }]

[source.x64]
url = "https://github.com/feenkcom/gtoolkit/releases/download/v1.1.529/GlamorousToolkit-Windows-x86_64-v1.1.529.zip"
sha256 = "afcad06cc9a417be04e2c620fe3f4b51e18af5a493f71983ebeed86f96408173"

[source.arm64]
url = "https://github.com/feenkcom/gtoolkit/releases/download/v1.1.529/GlamorousToolkit-Windows-aarch64-v1.1.529.zip"
sha256 = "82100eb8cc9516f6e5d16f516c1e5636d1bd613da0cb9a4ad1167bfd803d43f2"

[autoupdate]
checkver = { github = "feenkcom/gtoolkit" }
