name = "smartgit"
version = "26.1.052"
description = "A graphical Git client with support for SVN and Pull Requests for GitHub and Bitbucket."
homepage = "https://www.smartgit.dev/"
license = "Proprietary"
kind = "app"
extract_dir = "SmartGit"
bin = ["bin\\smartgitc.exe", { name = "smartgit", path = "bin\\smartgitc.exe" }]
shortcuts = [{ target = "bin\\smartgit.exe", name = "SmartGit" }]
persist = [".settings"]

[source.x64]
url = "https://download.smartgit.dev/smartgit/smartgit-26_1_052-win-portable.7z"
sha256 = "fda7c355e54f0920ba8c21f879c875f11e91316130f7df50c275b80b4e0793f7"

[autoupdate]
checkver = { url = "https://www.smartgit.dev/download/", regex = ">Version ([\\d.]+)<" }
