name = "nunit-console"
version = "3.22.0"
description = "NUnit Console runner for NUnit, the most popular and widely used unit testing framework for .NET"
homepage = "https://nunit.org/"
license = "MIT"
kind = "app"
extract_dir = "tools"
bin = ["nunit3-console.exe"]

[source.x64]
url = "https://github.com/nunit/nunit-console/releases/download/3.22.0/nunit-console-runner.3.22.0.nupkg"
sha256 = "d338f464ce56d99d02eec21359334729750fab47f5b4b91435ffad5a0151484c"

[autoupdate]
checkver = "{\"github\":\"https://api.github.com/repos/nunit/nunit-console/releases\",\"jsonpath\":\"$[?(@.prerelease == false)].tag_name\",\"regex\":\"\\\"(?:v|V)?([\\\\d.]+)\\\"\"}"
url_template = "https://github.com/nunit/nunit-console/releases/download/$version/nunit-console-runner.$version.nupkg"
