name = "rustic"
version = "0.11.3"
description = "fast, encrypted, and deduplicated backups powered by Rust"
homepage = "https://rustic.cli.rs"
license = "MIT|Apache-2.0"
kind = "app"
bin = ["rustic.exe"]
persist = ["config", "logs"]

[source.x64]
url = "https://github.com/rustic-rs/rustic/releases/download/v0.11.3/rustic-v0.11.3-x86_64-pc-windows-msvc.tar.gz"
sha256 = "b5c13f4fe7ce666ed5bae4d2a3128626399087c52650eebb6da0d10fb3640162"

[env]
RUSTIC_HOME = "{dir}"

[autoupdate]
checkver = { github = "rustic-rs/rustic" }
