name = "corretto16-jdk"
version = "16.0.2.7.1"
description = "Amazon Corretto is a no-cost, multiplatform, production-ready distribution of the Open Java Development Kit (OpenJDK)"
homepage = "https://aws.amazon.com/corretto/"
license = "GPL-2.0-only WITH Classpath-exception-2.0"
kind = "app"

[source.x64]
url = "https://corretto.aws/downloads/resources/16.0.2.7.1/amazon-corretto-16.0.2.7.1-windows-x64-jdk.zip"
sha256 = "d3a1790dabe0a11f57a84db9bf28cab6fe658757ff43248cea14eb4ba32f314f"

[env]
PATH = "{dir}\\bin"
JAVA_HOME = "{dir}"

[autoupdate]
checkver = "{\"jsonpath\":\"$.windows.x64.jdk.16.zip.resource\",\"regex\":\"/([\\\\d.]+)/\",\"url\":\"https://github.com/corretto/corretto-downloads/raw/main/latest_links/indexmap_with_checksum.json\"}"
