name = "proton-pass"
version = "1.37.0"
description = "Free password manager with identity protection by Proton."
homepage = "https://proton.me/pass"
license = "GPL-3.0-only"
kind = "app"
extract_dir = "lib\\net45"
shortcuts = [{ target = "ProtonPass.exe", name = "Proton\\Proton Pass" }]

[source.x64]
url = "https://proton.me/download/pass/windows/ProtonPass-1.37.0-full.nupkg"
sha256 = "b263c099225e045c2a03dc4cb355065f0fe0a5af6987e66168682d6e8ce3dc79"

[autoupdate]
checkver = "{\"jsonpath\":\"$.Releases[?(@.CategoryName == 'Stable')].Version\",\"url\":\"https://proton.me/download/pass/windows/version.json\"}"
url_template = { x64 = "https://proton.me/download/pass/windows/ProtonPass-$version-full.nupkg" }
