name = "air"
version = "1.67.3"
description = "A live-reloading command line utility for developing Go applications."
homepage = "https://github.com/air-verse/air"
license = "GPL-3.0-or-later"
kind = "app"
bin = ["air.exe"]

[source.x64]
url = "https://github.com/air-verse/air/releases/download/v1.67.3/air_1.67.3_windows_amd64.tar.gz"
sha256 = "150ab78cf4a48f46ca845660b41a913b0bae94572c061ea5dbe75cd745849a5a"

[autoupdate]
checkver = { github = "air-verse/air" }
