name = "s3browser"
version = "13.6.3"
description = "S3 Browser is a freeware Windows client for Amazon S3 and Amazon CloudFront."
homepage = "https://s3browser.com/"
license = "Freeware"
kind = "app"
extract_dir = "CS Browser"
bin = ["s3browser-cli.exe"]
shortcuts = [{ target = "s3browser-ui.exe", name = "S3Browser" }]

[source.x64]
url = "https://s3browser.com/download/s3browser-13-6-3.zip"
sha256 = "90c04a06377c2fbd899ed0ba444a1f1861cb68a3337d2d62f6d86e69903410b3"

[autoupdate]
checkver = { url = "https://s3browser.com/download.aspx", regex = "CS Browser Version (?<version>[\\d\\.]+)" }
