name = "openliberty"
version = "26.0.0.8"
description = "Server runtime available to JavaTM developers"
homepage = "https://openliberty.io/"
license = "EPL-1.0"
kind = "app"
extract_dir = "wlp"
bin = ["bin\\binaryLog.bat", { name = "wlp-client", path = "bin\\client.bat" }, "bin\\ddlGen.bat", "bin\\pluginUtility.bat", "bin\\productInfo.bat", "bin\\securityUtility.bat", { name = "wlp", path = "bin\\server.bat" }, "bin\\serverSchemaGen.bat", "bin\\springBootUtility.bat"]
persist = ["usr"]

[source.x64]
url = "https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/26.0.0.8/openliberty-26.0.0.8.zip"
sha256 = "d0682d4a72c13a4955145aa97fae2e432e40fd1b1bc076f0282bfafe02561b81"

[autoupdate]
checkver = { url = "https://openliberty.io/api/builds/data", regex = "openliberty-([\\d.]+)\\.zip" }
url_template = "https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/$version/openliberty-$version.zip"
