name = "intellij-jbr17-sdk-jcef"
version = "17.0.14-b1367.22"
description = "A fork of OpenJDK that includes a number enhancements in font rendering, HiDPI support, ligatures, performance improvements, and bugfixes. These are mainly for running IntelliJ Platform-based products"
homepage = "https://github.com/JetBrains/JetBrainsRuntime"
license = "GPL-2.0"
kind = "app"
extract_dir = "jbrsdk_jcef-17.0.14-windows-x64-b1367.22"

[source.x64]
url = "https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-17.0.14-windows-x64-b1367.22.tar.gz"
sha512 = "4f1627767b111fda2d9e79d84955876f39244b48a7d106caa923fbafa918b3ff591567aac8ff4c8c84ca21be00b12d0877688634950efb4c32249d547f329b88"

[source.arm64]
url = "https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-17.0.14-windows-aarch64-b1367.22.tar.gz"
sha512 = "0285604bd90b8b8ec19489712d8f8f2a86b60c87dbe19c6edae24fa85d6bce6a1df453ea109b7ecaded7b1c4468451e14bba0f3a1f645b3164ff1486b3bb0c9c"

[env]
JAVA_HOME = "{dir}"
PATH = "{dir}\\bin"

[autoupdate]
checkver = { github = "JetBrains/JetBrainsRuntime" }
