name = "dotmemoryunit"
version = "3.2.20220510"
description = "JetBrains dotMemory unit testing framework for testing .NET memory issues."
homepage = "https://www.jetbrains.com/dotmemory/unit"
license = "Freeware"
kind = "app"
bin = ["dotMemoryUnit.exe"]

[source.x64]
url = "https://download.jetbrains.com/resharper/JetBrains.dotMemoryUnit.3.2.20220510.zip"
sha256 = "6f85246c8828b7d874d21befa403b866fd87a4a51f1bff19ec5f3d559b55c1ab"

[autoupdate]
checkver = { url = "https://data.services.jetbrains.com/products/releases?code=DMU&latest=true&platform=zip&type=release", regex = "dotMemoryUnit\\.([\\d.]+)\\.zip" }
url_template = "https://download.jetbrains.com/resharper/JetBrains.dotMemoryUnit.$version.zip"
