name = "floorp"
version = "12.17.2"
description = "A Browser build for keeping the Open, Private and Sustainable Web alive. Based on Mozilla Firefox."
homepage = "https://github.com/Floorp-Projects"
license = "MPL-2.0"
kind = "app"
bin = ["floorp-portable.exe", "app\\floorp.exe"]
persist = ["data"]

[source.x64]
url = "https://github.com/Floorp-Projects/Floorp-Portable-v2/releases/download/v12.17.2/floorp-windows-x86_64.portable.7z"
sha256 = "246adeb0e4e7dbf547dbec454f468b601c3b19337367919a71bb6789e7244851"

[autoupdate]
checkver = { github = "Floorp-Projects/Floorp-Portable-v2" }
