name = "apache"
version = "2.4.69"
description = "The Apache HTTP Server ('httpd')"
homepage = "https://www.apachelounge.com"
license = "Apache-2.0"
kind = "app"
extract_dir = "Apache24"
bin = ["bin\\ab.exe", "bin\\abs.exe", "bin\\htcacheclean.exe", "bin\\htdbm.exe", "bin\\htdigest.exe", "bin\\htpasswd.exe", "bin\\httpd.exe", "bin\\httxt2dbm.exe", "bin\\logresolve.exe", "bin\\rotatelogs.exe"]
persist = ["htdocs", "conf", "logs"]

[source.x64]
url = "https://fossies.org/windows/www/httpd-2.4.69-261002-Win64-VS18.zip"
sha256 = "9b47a2363a71fef6209c88e79743db81311e1753c4564e007141934123132c10"

[autoupdate]
checkver = { url = "https://fossies.org/windows/www/", regex = "httpd-([\\d.]+)-(?<date>[\\d]+)-(?<arch>(w|W)in64)-(?<vs>VS\\d+)\\.zip" }
url_template = { x64 = "https://fossies.org/windows/www/httpd-$version-$matchDate-$matchArch-$matchVs.zip" }
