name = "resharper-clt"
version = "2026.2.0.2"
description = "A standalone command line tools to run ReSharper inspections outside of Visual Studio."
homepage = "https://www.jetbrains.com/resharper/download/index.html#section=resharper-clt"
license = "Freeware"
kind = "app"
bin = ["cleanupcode.exe", "inspectcode.exe"]

[source.x64]
url = "https://download.jetbrains.com/resharper/dotUltimate.2026.2.0.2/JetBrains.ReSharper.CommandLineTools.2026.2.0.2.zip"
sha256 = "f5dd6f30e57fac1359423b70095ab951242e4866416853719691c6c0f22620a1"

[autoupdate]
checkver = "{\"jsonpath\":\"$.RSCLT.[0].version\",\"url\":\"https://data.services.jetbrains.com/products/releases?code=RSCLT&latest=true&type=release\"}"
url_template = "https://download.jetbrains.com/resharper/dotUltimate.$version/JetBrains.ReSharper.CommandLineTools.$version.zip"
