name = "spotbugs"
version = "4.10.3"
description = "Static analysis tool for Java"
homepage = "https://spotbugs.github.io/"
license = "LGPL-2.1-only"
kind = "app"
extract_dir = "spotbugs-4.10.3"
bin = ["bin\\spotbugs.bat"]
persist = ["plugin"]

[source.x64]
url = "https://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs/4.10.3/spotbugs-4.10.3.zip"
sha256 = "e814ee5bf9665412658c4d684e45eae3cf993148a71bc8bc93fb343e92288151"

[autoupdate]
checkver = "{\"regex\":\"spotbugs ([\\\\d.]+) documentation\",\"url\":\"https://spotbugs.readthedocs.io/en/stable/installing.html\"}"
