name = "smoothcsv"
version = "3.23.1"
description = "A powerful and intuitive tool for editing CSV files."
homepage = "https://smoothcsv.com/"
license = "Freeware"
kind = "app"
bin = ["bin\\smoothcsv.exe"]
persist = ["data"]

[source.x64]
url = "https://github.com/kohii/smoothcsv3/releases/download/v3.23.1/SmoothCSV_3.23.1_x64_portable.zip"
sha256 = "662a18a74a294433c509cc093f907d9689ba94b8855e63e4c9df6796977bcbcf"

[source.arm64]
url = "https://github.com/kohii/smoothcsv3/releases/download/v3.23.1/SmoothCSV_3.23.1_arm64_portable.zip"
sha256 = "6a530e15c8ed1ebc5746d5011a72625796bb7ac835c4439c6d868db0478dc752"

[autoupdate]
checkver = { github = "kohii/smoothcsv3" }
