name = "mongodb-compass"
version = "1.49.12"
description = "An interactive tool for querying, optimizing, and analyzing MongoDB data"
homepage = "https://www.mongodb.com/products/compass"
license = "SSPL-1.0"
kind = "app"

[source.x64]
url = "https://downloads.mongodb.com/compass/mongodb-compass-1.49.12-win32-x64.zip"
sha256 = "9675cea7e076f2f308ed2caa6407e9c4f3dd30ea6536f5418c36917ed1fe4145"

[autoupdate]
checkver = "{\"regex\":\"mongodb-compass-([\\\\d.]+)-win32-x64.zip\",\"url\":\"https://www.mongodb.com/try/download/compass\"}"
