name = "moon"
version = "2.5.6"
description = "A task runner and monorepo management tool for the web ecosystem, written in Rust."
homepage = "https://moonrepo.dev/moon"
license = "MIT"
kind = "app"
bin = ["moon.exe"]

[source.x64]
url = "https://github.com/moonrepo/moon/releases/download/v2.5.6/moon_cli-x86_64-pc-windows-msvc.zip"
sha256 = "42c4f0a9de29d1ef7b7f312a496ddb48adf8757318d4ed8bad1224d7e1021950"

[autoupdate]
checkver = { github = "moonrepo/moon" }
url_template = { x64 = "https://github.com/moonrepo/moon/releases/download/v$version/moon_cli-x86_64-pc-windows-msvc.zip" }
