name = "tssh"
version = "0.1.25"
description = "A highly OpenSSH-compatible client with extended features."
homepage = "https://trzsz.github.io/tssh"
license = "MIT"
kind = "app"
extract_dir = "tssh_0.1.25_windows_x86_64"
bin = ["tssh.exe"]

[source.x64]
url = "https://github.com/trzsz/trzsz-ssh/releases/download/v0.1.25/tssh_0.1.25_windows_x86_64.zip"
sha256 = "a1ac7631ed567c3fb8edd4c66114aa0620aaca525980a689d341ec78060f5a29"

[source.arm64]
url = "https://github.com/trzsz/trzsz-ssh/releases/download/v0.1.25/tssh_0.1.25_windows_aarch64.zip"
sha256 = "ee68779a742cec99bae889c581a124677d49ce7540c0cef0d7e842e16eb76314"

[autoupdate]
checkver = { github = "trzsz/trzsz-ssh" }
