name = "edgedriver"
version = "150.0.4078.99"
description = "Close the loop on your developer cycle by automating testing of your website in Microsoft Edge (Chromium)."
homepage = "https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver"
license = "Freeware"
kind = "app"
bin = ["msedgedriver.exe"]

[source.x64]
url = "https://msedgedriver.microsoft.com/150.0.4078.99/edgedriver_win64.zip"
sha256 = "916b30880b0c494332fa8ee9736dc444df43eeca3055b91f4f41d5153807ee6c"

[source.arm64]
url = "https://msedgedriver.microsoft.com/150.0.4078.99/edgedriver_arm64.zip"
sha256 = "ee514d64e6cdd77cb41e44b4abbc2d246d14991ad09f9aafec9c9498dc0b2c64"

[autoupdate]
checkver = "{\"regex\":\"([\\\\d.]+)\",\"script\":\"Write-Output $([System.Text.Encoding]::Unicode.GetString((Invoke-WebRequest -URI https://msedgedriver.microsoft.com/LATEST_STABLE).Content))\"}"
url_template = { x64 = "https://msedgedriver.microsoft.com/$version/edgedriver_win64.zip", arm64 = "https://msedgedriver.microsoft.com/$version/edgedriver_arm64.zip" }
