name = "gridplayer"
version = "0.5.5"
description = "Play videos side-by-side"
homepage = "https://github.com/vzhd1701/gridplayer"
license = "GPL-3.0-only"
kind = "app"
persist = ["portable_data"]

[source.x64]
url = "https://github.com/vzhd1701/gridplayer/releases/download/v0.5.5/GridPlayer-0.5.5-win64-portable.zip"
sha256 = "13a7e2ff20267bd902128e4ab07edce135615f1c94efabc327b13c4ec0a94d3d"

[autoupdate]
checkver = { github = "vzhd1701/gridplayer" }
