name = "jmeter"
version = "5.6.3"
description = "Application designed to load test functional behavior and measure performance."
homepage = "https://jmeter.apache.org"
license = "Apache-2.0"
kind = "app"
extract_dir = "apache-jmeter-5.6.3"
bin = ["bin\\jmeter.bat", "bin\\jmeterw.cmd", "bin\\jmeter-n.cmd", "bin\\jmeter-n-r.cmd", "bin\\jmeter-t.cmd", "bin\\jmeter-server.bat", "bin\\mirror-server.cmd", { name = "jmeter-shutdown", path = "bin\\shutdown.cmd" }, { name = "jmeter-stoptest", path = "bin\\stoptest.cmd" }]
shortcuts = [{ target = "bin\\jmeterw.cmd", name = "JMeter" }, { target = "bin\\jmeter.bat", name = "JMeter (with console)" }]
persist = ["lib"]

[source.x64]
url = "https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.zip"
sha512 = "387fadca903ee0aa30e3f2115fdfedb3898b102e6b9fe7cc3942703094bd2e65b235df2b0c6d0d3248e74c9a7950a36e42625fd74425368342c12e40b0163076"

[env]
JMETER_HOME = "{dir}"

[autoupdate]
checkver = { url = "https://jmeter.apache.org/changes.html", regex = ">Version ([\\d.]+)" }
url_template = "https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$version.zip"
