name = "zeebe"
version = "8.9.21"
description = "Distributed Workflow Engine for Microservices Orchestration"
homepage = "https://camunda.com/products/cloud/workflow-engine/"
license = "Zeebe Community License v1.0"
kind = "app"
extract_dir = "camunda-zeebe-8.9.21"
bin = [{ name = "zeebe-broker", path = "bin\\broker.bat" }, { name = "zeebe-gateway", path = "bin\\gateway.bat" }]

[source.x64]
url = "https://github.com/camunda/camunda/releases/download/8.9.21/camunda-zeebe-8.9.21.zip"
sha256 = "b5001915eb59f8ecfaaf764cdba67e8d0978d2f0ff2a17c37655b33db49e71bf"

[autoupdate]
checkver = { github = "camunda/camunda" }
url_template = { x64 = "https://github.com/camunda/camunda/releases/download/$version/camunda-zeebe-$version.zip" }
