name = "codetrack"
version = "1.0.3.3"
description = "A free .NET performance profiler and execution analyzer."
homepage = "https://www.getcodetrack.com"
license = "Freeware"
kind = "app"
bin = ["CodeTrack.exe"]
shortcuts = [{ target = "CodeTrack.exe", name = "CodeTrack" }]

[source.x64]
url = "https://www.getcodetrack.com/releases/codetrack_1_0_3_3.zip"
sha256 = "455eccfcc568004bf6108ba9ad8dbbc32cdecb84c6c62153c8f181ca984d68ce"

[autoupdate]
checkver = "{\"regex\":\">V([\\\\d.]+)<\",\"url\":\"https://www.getcodetrack.com/releases.html\"}"
