name = "apk-editor-studio"
version = "1.7.2"
description = "Powerful yet easy to use APK editor for PC and Mac."
homepage = "https://github.com/kefir500/apk-editor-studio"
license = "GPL-3.0"
kind = "app"
extract_dir = "APK Editor Studio v1.7.2"
shortcuts = [{ target = "apk-editor-studio.exe", name = "APK Editor Studio" }]
persist = ["tools"]

[source.x64]
url = "https://github.com/kefir500/apk-editor-studio/releases/download/v1.7.2/apk-editor-studio_windows_1.7.2.zip"
sha256 = "66e545542d1e856b4401c3ae07346fb994bd52754b3cbbbd21a1cd4d0f95b1b0"

[autoupdate]
checkver = { github = "kefir500/apk-editor-studio" }
url_template = { x64 = "https://github.com/kefir500/apk-editor-studio/releases/download/v$version/apk-editor-studio_windows_$version.zip" }
