name = "v2rayn"
version = "7.24.9"
description = "v2rayN (WPF-based version) is a GUI client for V2Ray, with support for Xray, sing-box, and other compatible cores."
homepage = "https://github.com/2dust/v2rayN"
license = "GPL-3.0-only"
kind = "app"
shortcuts = [{ target = "v2rayN.exe", name = "v2rayN" }]
persist = ["guiConfigs"]

[source.x64]
url = "https://github.com/2dust/v2rayN/releases/download/7.24.9/v2rayN-windows-64.zip"
sha256 = "84a3b7d249db0c87951566f3fa4af520d97115469a404e1d3d506096f6186685"
extract_dir = "v2rayN-windows-64"

[source.arm64]
url = "https://github.com/2dust/v2rayN/releases/download/7.24.9/v2rayN-windows-arm64.zip"
sha256 = "f8e007a614cec5b96eea64cb05b9694d39b0946f6e3920285f8beead24029cc5"
extract_dir = "v2rayN-windows-arm64"

[autoupdate]
checkver = { github = "2dust/v2rayN" }
url_template = { x64 = "https://github.com/2dust/v2rayN/releases/download/$version/v2rayN-windows-64.zip", arm64 = "https://github.com/2dust/v2rayN/releases/download/$version/v2rayN-windows-arm64.zip" }
