name = "slack"
version = "4.52.171"
description = "Collaboration software"
homepage = "https://slack.com"
license = "Freeware"
kind = "app"
extract_dir = "app"
bin = ["slack.exe"]
shortcuts = [{ target = "slack.exe", name = "Slack" }]

[source.x64]
url = "https://downloads.slack-edge.com/desktop-releases/windows/x64/4.52.171/Slack.msix#/dl.zip"
sha256 = "c09f8097c08e5179679262e0f88dd2fc7eed3004285b3d0cb23add822b9f3817"

[source.arm64]
url = "https://downloads.slack-edge.com/desktop-releases/windows/arm64/4.52.171/Slack.msix#/dl.zip"
sha256 = "e5d36004f24963ad423864786e80ada9e5a6db61413c914c4c1a4745ba19e407"

[autoupdate]
checkver = { url = "https://slack.com/release-notes/windows", regex = "<h2 .+?>Slack ([\\d.]+)" }
url_template = { x64 = "https://downloads.slack-edge.com/desktop-releases/windows/x64/$version/Slack.msix#/dl.zip", arm64 = "https://downloads.slack-edge.com/desktop-releases/windows/arm64/$version/Slack.msix#/dl.zip" }
