name = "intellij-jbr25-jcef"
version = "25.0.3-b508.16"
description = "A fork of OpenJDK that supports enhanced class redefinition (DCEVM), features optional JCEF, a framework for embedding Chromium-based browsers, includes a number of improvements in font rendering, keyboards support, windowing/focus subsystems, HiDPI, accessibility, and performance, provides better desktop integration and bugfixes not yet present in OpenJDK."
homepage = "https://github.com/JetBrains/JetBrainsRuntime"
license = "GPL-2.0-only"
kind = "app"
extract_dir = "jbr_jcef-25.0.3-windows-x64-b508.16"

[source.x64]
url = "https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-25.0.3-windows-x64-b508.16.tar.gz"
sha512 = "888d3c013885754f9581492670c2aa2dde013b1d55fba03ee96d36e2904913d0b420e70a0d7ef3a4c8b0de599f2f6fe8d1dc84b78186a60167ecbcaebd2dc455"

[source.arm64]
url = "https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-25.0.3-windows-aarch64-b508.16.tar.gz"
sha512 = "7ceaeccc50ca698d918b9cfb208b4a0ea3f605d4bc440f380ba5492b864bbf506d14ae5c731089cfa5e1707c033eecbbd8ac1fd90980855a01e342a5e63efdc1"

[env]
JAVA_HOME = "{dir}"
PATH = "{dir}\\bin"

[autoupdate]
checkver = { github = "JetBrains/JetBrainsRuntime" }
