name = "semeru18-jdk"
version = "18.0.2-9-0.33.1"
description = "The IBM Semeru Runtimes are free production-ready binaries built with the OpenJDK class libraries and the Eclipse OpenJ9 JVM"
homepage = "https://developer.ibm.com/languages/java/semeru-runtimes/"
license = "GPL-2.0-only WITH Classpath-exception-2.0,EPL-2.0"
kind = "app"

[source.x64]
url = "https://github.com/ibmruntimes/semeru18-binaries/releases/download/jdk-18.0.2%2B9_openj9-0.33.1/ibm-semeru-open-jdk_x64_windows_18.0.2_9_openj9-0.33.1.zip"
sha256 = "cba270f40308ac503a039bb9f53becc0da679e550b019ed6721634229b1e65f8"

[env]
JAVA_HOME = "{dir}"
PATH = "{dir}\\bin"

[autoupdate]
checkver = { github = "ibmruntimes/semeru18-binaries" }
