name = "jenv"
version = "2.2.1"
description = "Change your current Java version with one line"
homepage = "https://github.com/FelixSelter/JEnv-for-Windows"
license = "Apache-2.0"
kind = "app"
bin = ["jenv.bat", "java.bat"]

[source.x64]
url = "https://github.com/FelixSelter/JEnv-for-Windows/releases/download/v2.2.1/JEnv.zip"
sha256 = "11c0f3f18f531d4c664e2e39c1a39b3432e92252d5f7aab421846233b607ec3c"

[autoupdate]
checkver = { github = "FelixSelter/JEnv-for-Windows" }
