name = "throne"
version = "1.2.1"
description = "Cross-platform GUI proxy utility (Empowered by sing-box)"
homepage = "https://github.com/throneproj/throne"
license = "GPL-3.0-only"
kind = "app"
extract_dir = "Throne"
shortcuts = [{ target = "Throne.exe", name = "Throne" }]
persist = ["config"]

[source.x64]
url = "https://github.com/throneproj/throne/releases/download/1.2.1/Throne-1.2.1-windows64.zip"
sha256 = "ed5b3b2dc20f9b5a565dc041e5388c6a27f3c66ad5cd8229a52ac2e854f493d0"

[source.arm64]
url = "https://github.com/throneproj/throne/releases/download/1.2.1/Throne-1.2.1-windows-arm64.zip"
sha256 = "47fe31960ab18b2d1f5b19f06ea97ae18967a924b7b4595acd20a08b846cb6ea"

[autoupdate]
checkver = { github = "throneproj/throne" }
url_template = { x64 = "https://github.com/throneproj/throne/releases/download/$version/Throne-$version-windows64.zip", arm64 = "https://github.com/throneproj/throne/releases/download/$version/Throne-$version-windows-arm64.zip" }
