name = "sbt"
version = "2.0.3"
description = "A build tool for Scala, Java, and more"
homepage = "https://www.scala-sbt.org"
license = "BSD-3-Clause"
kind = "app"
extract_dir = "sbt"
bin = ["bin\\sbt.bat"]
persist = ["conf"]

[source.x64]
url = "https://github.com/sbt/sbt/releases/download/v2.0.3/sbt-2.0.3.zip"
sha256 = "f85f15467222b38e57fa346cf82d3c2c0d680a39c1ba997627739772ce5462d8"

[env]
SBT_HOME = "{dir}"

[autoupdate]
checkver = "{\"regex\":\"/sbt-([\\\\d.]+)\\\\.zip\",\"url\":\"https://www.scala-sbt.org/download/\"}"
