name = "codesnap"
version = "0.13.4"
description = "Command-line tool for generating beautiful code snippets"
homepage = "https://github.com/codesnap-rs/codesnap"
license = "MIT"
kind = "app"
bin = ["codesnap.exe"]

[source.x64]
url = "https://github.com/codesnap-rs/codesnap/releases/download/v0.13.4/codesnap-cli_v0.13.4_x86_64-pc-windows-msvc.zip"
sha256 = "631a669a61b09294badaea19ef2d15cfa30aaa1b456ade7862fd6530604dcd91"

[autoupdate]
checkver = { github = "codesnap-rs/codesnap" }
url_template = { x64 = "https://github.com/codesnap-rs/codesnap/releases/download/v$version/codesnap-cli_v$version_x86_64-pc-windows-msvc.zip" }
