name = "jsonschema"
version = "16.8.0"
description = "JSON Schema formatting, linting, testing, bundling and more for local development and CI/CD pipelines."
homepage = "https://github.com/sourcemeta/jsonschema"
license = "AGPL-3.0-or-later"
kind = "app"
extract_dir = "jsonschema-16.8.0-windows-x86_64"
bin = ["bin\\jsonschema.exe"]

[source.x64]
url = "https://github.com/sourcemeta/jsonschema/releases/download/v16.8.0/jsonschema-16.8.0-windows-x86_64.zip"
sha256 = "d0419f909d746be563b4e5be74d8457f214db429defa1096c25f333e55ce3f82"

[autoupdate]
checkver = { github = "sourcemeta/jsonschema" }
url_template = { x64 = "https://github.com/sourcemeta/jsonschema/releases/download/v$version/jsonschema-$version-windows-x86_64.zip" }
