name = "jsonschema"
version = "17.0.0"
description = "JSON Schema formatting, linting, testing, bundling and more for local development and CI/CD pipelines."
homepage = "https://github.com/sourcemeta/jsonschema"
license = "AGPL-3.0-or-later"
kind = "app"
extract_dir = "jsonschema-17.0.0-windows-x86_64"
bin = ["bin\\jsonschema.exe"]

[source.x64]
url = "https://github.com/sourcemeta/jsonschema/releases/download/v17.0.0/jsonschema-17.0.0-windows-x86_64.zip"
sha256 = "957a57e571f43de559e8a0d32bafb1387db77f867b53e212d19471b03aeeccaf"

[autoupdate]
checkver = { github = "sourcemeta/jsonschema" }
url_template = { x64 = "https://github.com/sourcemeta/jsonschema/releases/download/v$version/jsonschema-$version-windows-x86_64.zip" }
