name = "ausweisapp2"
version = "2.5.5"
description = "Authenticate to websites with german ID."
homepage = "https://www.ausweisapp.bund.de/"
license = "EUPL-1.2"
kind = "app"
extract_dir = "PFiles64\\AusweisApp"
shortcuts = [{ target = "AusweisApp.exe", name = "AusweisApp" }]

[source.x64]
url = "https://github.com/Governikus/AusweisApp/releases/download/2.5.5/AusweisApp-2.5.5.msi"
sha256 = "5795694ee178ecbbfab28031099e1bc23d27aaa3eb937d14b548129c0587f51f"
kind = "installer-archive"

[autoupdate]
checkver = { github = "Governikus/AusweisApp" }
url_template = { x64 = "https://github.com/Governikus/AusweisApp/releases/download/$version/AusweisApp-$version.msi" }
