name = "auto-dark-mode"
version = "11.0.0.54"
description = "Automatically switches between the dark and light theme of Windows 10 and Windows 11."
homepage = "https://github.com/AutoDarkMode/Windows-Auto-Night-Mode"
license = "GPL-3.0-only"
kind = "app"
bin = ["core\\AutoDarkModeShell.exe"]

[source.x64]
url = "https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/download/11.0.0.54/AutoDarkMode_11.0.0.54_x64.zip"
sha256 = "4323e639fb363a90b3ca7de0e9523bdfd7e09bc45bb272f5eb6f2ccc8651b512"

[source.arm64]
url = "https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/download/11.0.0.54/AutoDarkMode_11.0.0.54_ARM64.zip"
sha256 = "dfd300b0d10196ea05dd016c41fbc90219301512de5130a78ca82bdc833c56cc"

[autoupdate]
checkver = { github = "AutoDarkMode/Windows-Auto-Night-Mode" }
