name = "stripe-cli"
version = "1.45.1"
description = "Officially command-line tool for Stripe."
homepage = "https://stripe.com/docs/stripe-cli"
license = "Apache-2.0"
kind = "app"
bin = ["stripe.exe"]

[source.x64]
url = "https://github.com/stripe/stripe-cli/releases/download/v1.45.1/stripe_1.45.1_windows_x86_64.zip"
sha256 = "6113676359d7b2529fb92eba7dcdd326c15092cc5bd531a82e68876258c9c0a7"

[autoupdate]
checkver = { github = "stripe/stripe-cli" }
url_template = { x64 = "https://github.com/stripe/stripe-cli/releases/download/v$version/stripe_$version_windows_x86_64.zip" }
