name = "tabula"
version = "1.2.1"
description = "A tool for liberating data tables trapped inside PDF files."
homepage = "https://tabula.technology/"
license = "MIT"
kind = "app"
extract_dir = "tabula"
bin = ["tabula.exe"]
shortcuts = [{ target = "tabula.exe", name = "tabula" }]

[source.x64]
url = "https://github.com/tabulapdf/tabula/releases/download/v1.2.1/tabula-win-1.2.1.zip"
sha256 = "a5bd9afd969c7488f91ea3a7a09d56a1b53fe86ee231b81d205a8c1a9d459a05"

[autoupdate]
checkver = { github = "tabulapdf/tabula" }
url_template = "https://github.com/tabulapdf/tabula/releases/download/v$version/tabula-win-$version.zip"
