name = "metabase"
version = "0.63.15"
description = "The simplest, fastest way to get business intelligence and analytics to everyone in your company"
homepage = "https://www.metabase.com"
license = "AGPL-3.0-or-later"
kind = "app"
bin = ["metabase.jar"]

[source.x64]
url = "https://downloads.metabase.com/v0.63.15/metabase.jar"
sha256 = "95268773d0eb8bef6ee0d57bc1dd6c352288e94279fdf85f0377be92c0f29c7f"

[autoupdate]
checkver = { github = "metabase/metabase" }
url_template = "https://downloads.metabase.com/v$version/metabase.jar"
