name = "metabase"
version = "0.63.19"
description = "The simplest, fastest way to get business intelligence and analytics to everyone in your company"
homepage = "https://www.metabase.com"
license = "AGPL-3.0-or-later"
kind = "app"
bin = ["metabase.jar"]

[source.x64]
url = "https://downloads.metabase.com/v0.63.19/metabase.jar"
sha256 = "d4695f2d4b0e0ba79f37d39b2a1ae9937d1e133aff813c33c0772a6329b2af02"

[autoupdate]
checkver = { github = "metabase/metabase" }
url_template = "https://downloads.metabase.com/v$version/metabase.jar"
