name = "marble"
version = "2.2.0"
description = "A virtual globe and world atlas — your swiss army knife for maps."
homepage = "https://marble.kde.org/index.php"
license = "LGPL-2.1-only"
kind = "app"
shortcuts = [{ target = "marble-qt.exe", name = "Marble" }]

[source.x64]
url = "https://files.kde.org/marble/downloads/windows/Marble-setup_2.2.0-1_x64.exe"
sha256 = "10b47fb07cae61d48ea9ade811261d3a7ff26b5e96f362e663a583d4d8773e10"
kind = "installer-archive"

[autoupdate]
checkver = { url = "https://marble.kde.org/install.php?", regex = "Marble-setup_(?<version>[\\d.]+)(?<release>-?[\\d+]?)_x64\\.exe" }
url_template = { x64 = "https://files.kde.org/marble/downloads/windows/Marble-setup_$version$matchRelease_x64.exe" }
