name = "onionshare"
version = "2.6.5"
description = "Securely and anonymously send and receive files."
homepage = "https://onionshare.org/"
license = "GPL-3.0-only"
kind = "app"
extract_dir = "OnionShare"
bin = [{ name = "onionshare", path = "onionshare-cli.exe" }]
shortcuts = [{ target = "onionshare.exe", name = "OnionShare" }]

[source.x64]
url = "https://github.com/onionshare/onionshare/releases/download/v2.6.5/OnionShare-win64-2.6.5.msi"
sha256 = "a33a29ae7bfea1b3633303272f42177f7fc9808dbbd21270ea48befecb69f67b"
kind = "installer-archive"

[autoupdate]
checkver = { github = "onionshare/onionshare" }
url_template = { x64 = "https://github.com/onionshare/onionshare/releases/download/v$version/OnionShare-win64-$version.msi" }
