name = "pe-bear"
version = "0.7.2"
description = "Reversing tool for PE files"
homepage = "https://hshrzd.wordpress.com/pe-bear/"
license = "GPL-2.0-only"
kind = "app"
bin = ["PE-bear.exe"]
shortcuts = [{ target = "PE-bear.exe", name = "PE-bear" }]

[source.x64]
url = "https://github.com/hasherezade/pe-bear/releases/download/v0.7.2/PE-bear_0.7.2_qt6_x64_win_vs22.zip"
sha256 = "d2b995b213d0e6b3910a863c12fdb842722ce47387e65fc8e711ee9013d0876e"

[autoupdate]
checkver = { github = "hasherezade/pe-bear" }
url_template = { x64 = "https://github.com/hasherezade/pe-bear/releases/download/v$version/PE-bear_$version_qt6_x64_win_vs22.zip" }
