//! Driver: read a Scoop `main` bucket clone, convert each manifest to voli
//! TOML, round-trip every emitted file through `voli_core::Manifest`, write
//! accepted packages under `manifests/<first-letter>/<name>/<version>.toml`,
//! and emit `manifests/_import-report.md`.
//!
//! Usage: scoop-import <scoop-main-dir> <out-manifests-dir>
//!
//! `<scoop-main-dir>` may be the repo root (containing `bucket/`) or the
//! `bucket/` dir itself.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use scoop_import::{Outcome, convert};
use voli_core::manifest::Manifest;

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().collect();
    if args.len() != 3 {
        eprintln!("usage: scoop-import <scoop-main-dir> <out-manifests-dir>");
        return ExitCode::FAILURE;
    }
    let bucket = locate_bucket(Path::new(&args[1]));
    let out = PathBuf::from(&args[2]);

    let mut jsons: Vec<PathBuf> = match fs::read_dir(&bucket) {
        Ok(rd) => rd
            .filter_map(Result::ok)
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|x| x == "json"))
            .collect(),
        Err(e) => {
            eprintln!("cannot read {}: {e}", bucket.display());
            return ExitCode::FAILURE;
        }
    };
    jsons.sort();

    let mut converted = 0usize;
    let mut skips: Vec<(String, &'static str)> = Vec::new();
    let mut roundtrip_failures: Vec<(String, String)> = Vec::new();

    for path in &jsons {
        let stem = path.file_stem().unwrap().to_string_lossy().into_owned();
        let text = match fs::read_to_string(path) {
            Ok(t) => t,
            Err(e) => {
                skips.push((stem, "read-error"));
                eprintln!("read {}: {e}", path.display());
                continue;
            }
        };
        let json: serde_json::Value = match serde_json::from_str(&text) {
            Ok(v) => v,
            Err(_) => {
                skips.push((stem, "json-parse-error"));
                continue;
            }
        };

        match convert(&stem, &json) {
            Outcome::Skip(reason) => skips.push((stem, reason)),
            Outcome::Ok(c) => {
                // Round-trip: a failure here is an emitter bug, not a skip.
                if let Err(e) = Manifest::from_toml_str(&c.toml) {
                    roundtrip_failures.push((c.name.clone(), e.to_string()));
                    eprintln!("ROUND-TRIP FAILED for {}: {e}\n{}", c.name, c.toml);
                    continue;
                }
                if let Err(e) = write_manifest(&out, &c.name, &c.version, &c.toml) {
                    eprintln!("write {}: {e}", c.name);
                    continue;
                }
                converted += 1;
            }
        }
    }

    let report = build_report(jsons.len(), converted, &skips, &roundtrip_failures);
    let report_path = out.join("_import-report.md");
    if let Err(e) = fs::write(&report_path, &report) {
        eprintln!("cannot write report {}: {e}", report_path.display());
        return ExitCode::FAILURE;
    }

    println!(
        "processed {} manifests: {converted} converted, {} skipped, {} round-trip failures",
        jsons.len(),
        skips.len(),
        roundtrip_failures.len()
    );
    println!("report: {}", report_path.display());

    // Round-trip failures mean the emitter is broken — fail loudly.
    if roundtrip_failures.is_empty() {
        ExitCode::SUCCESS
    } else {
        ExitCode::FAILURE
    }
}

fn locate_bucket(dir: &Path) -> PathBuf {
    let nested = dir.join("bucket");
    if nested.is_dir() {
        nested
    } else {
        dir.to_path_buf()
    }
}

fn write_manifest(out: &Path, name: &str, version: &str, toml: &str) -> std::io::Result<()> {
    let first = name.chars().next().unwrap_or('_').to_string();
    let dir = out.join(&first).join(name);
    fs::create_dir_all(&dir)?;
    fs::write(dir.join(format!("{}.toml", sanitize(version))), toml)
}

/// Make a version safe as a Windows filename component.
fn sanitize(version: &str) -> String {
    version
        .chars()
        .map(|c| {
            if matches!(c, '\\' | '/' | ':' | '*' | '?' | '"' | '<' | '>' | '|') {
                '_'
            } else {
                c
            }
        })
        .collect()
}

fn build_report(
    total: usize,
    converted: usize,
    skips: &[(String, &'static str)],
    roundtrip_failures: &[(String, String)],
) -> String {
    let mut by_reason: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for (name, reason) in skips {
        by_reason.entry(reason).or_default().push(name);
    }

    let mut o = String::new();
    o.push_str("# Scoop main → voli import report\n\n");
    o.push_str("Generated by `tools/scoop-import`. Source: ScoopInstaller/Main (MIT).\n\n");
    o.push_str("## Summary\n\n");
    o.push_str(&format!("- Total Scoop manifests: **{total}**\n"));
    o.push_str(&format!("- Converted: **{converted}**\n"));
    o.push_str(&format!("- Skipped: **{}**\n", skips.len()));
    if !roundtrip_failures.is_empty() {
        o.push_str(&format!(
            "- **Round-trip failures (emitter bugs): {}**\n",
            roundtrip_failures.len()
        ));
    }
    o.push('\n');

    o.push_str("## Skipped by reason\n\n");
    o.push_str("| Reason | Count |\n|---|---|\n");
    for (reason, names) in &by_reason {
        o.push_str(&format!("| {reason} | {} |\n", names.len()));
    }
    o.push('\n');

    if !roundtrip_failures.is_empty() {
        o.push_str("## Round-trip failures\n\n");
        for (name, err) in roundtrip_failures {
            o.push_str(&format!("- `{name}` — {err}\n"));
        }
        o.push('\n');
    }

    o.push_str("## Full skip list (hand-conversion worklist)\n\n");
    o.push_str("Sorted by reason, then name.\n\n");
    for (reason, names) in &by_reason {
        o.push_str(&format!("### {reason} ({})\n\n", names.len()));
        let mut sorted = names.clone();
        sorted.sort_unstable();
        for name in sorted {
            o.push_str(&format!("- {name}\n"));
        }
        o.push('\n');
    }

    o
}
