name = "yaak"
version = "2026.5.0"
description = "A fast, privacy-first API client for REST, GraphQL, SSE, WebSocket, and gRPC."
homepage = "https://yaak.app/"
license = "MIT"
kind = "app"
shortcuts = [{ target = "yaak-app-client.exe", name = "Yaak" }]

[source.x64]
url = "https://github.com/mountain-loop/yaak/releases/download/v2026.5.0/Yaak_2026.5.0_x64-setup.exe#/dl.7z"
sha256 = "29a9cb37473c3a0de234f8af4130b02f85537f17ac4b411bafc08411f1555f9f"

[autoupdate]
checkver = { github = "mountain-loop/yaak" }
