name = "fresh"
version = "0.4.9"
description = "Easy, powerful and fast text editor for your terminal."
homepage = "https://getfresh.dev"
license = "GPL-2.0-only"
kind = "app"
bin = ["fresh.exe"]

[source.x64]
url = "https://github.com/sinelaw/fresh/releases/download/v0.4.9/fresh-editor-x86_64-pc-windows-msvc.zip"
sha256 = "e71c322fc0d04b5fe250e1cb8fc6800de18e2eed7874545b8da875aa444f05f6"

[source.arm64]
url = "https://github.com/sinelaw/fresh/releases/download/v0.4.9/fresh-editor-aarch64-pc-windows-msvc.zip"
sha256 = "22cca603b8a1eca758d087124f375dc9261626a7b2e35e218ddb2cb0cd42125f"

[autoupdate]
checkver = { github = "sinelaw/fresh" }
url_template = { x64 = "https://github.com/sinelaw/fresh/releases/download/v$version/fresh-editor-x86_64-pc-windows-msvc.zip", arm64 = "https://github.com/sinelaw/fresh/releases/download/v$version/fresh-editor-aarch64-pc-windows-msvc.zip" }
