name = "docto"
version = "1.16"
description = "Simple command line utility for converting .doc & .xls files to any supported format."
homepage = "https://github.com/tobya/DocTo"
license = "MIT"
kind = "app"
bin = ["docto.exe"]

[source.x64]
url = "https://github.com/tobya/DocTo/releases/download/v1.16/docto_64.zip"
sha256 = "03f36e72a8d3de98dcdc031603fc5208a9887478b1fcbdb154dd7e632dda424f"

[autoupdate]
checkver = { github = "tobya/DocTo" }
url_template = { x64 = "https://github.com/tobya/DocTo/releases/download/v$version/docto_64.zip" }
