name = "kubelogin"
version = "1.36.3"
description = "kubectl plugin for Kubernetes OpenID Connect authentication (kubectl oidc-login)"
homepage = "https://github.com/int128/kubelogin"
license = "Apache-2.0"
kind = "app"
bin = ["kubelogin.exe", { name = "kubectl-oidc_login", path = "kubelogin.exe" }]

[source.x64]
url = "https://github.com/int128/kubelogin/releases/download/v1.36.3/kubelogin_windows_amd64.zip"
sha256 = "6f1ea25914fb5c1ae7c48bcb688bea37e54960a6143208c35b4fb506ac947611"

[autoupdate]
checkver = { github = "int128/kubelogin" }
url_template = { x64 = "https://github.com/int128/kubelogin/releases/download/v$version/kubelogin_windows_amd64.zip" }
