name = "micronaut"
version = "5.2.1"
description = "Micronaut - A modern, JVM-based (Java, Groovy, Kotlin), full-stack framework for building modular and testable microservice and serverless applications"
homepage = "https://micronaut.io"
license = "Apache-2.0"
kind = "app"
extract_dir = "micronaut-cli-5.2.1"
bin = ["bin\\mn.bat"]

[source.x64]
url = "https://github.com/micronaut-projects/micronaut-starter/releases/download/v5.2.1/micronaut-cli-5.2.1.zip"
sha256 = "082fbb8061cca91466bc9c90ccaa46c7d9f5ddaa38b1f0587a89c256b1775aee"

[env]
MICRONAUT_HOME = "{dir}"

[autoupdate]
checkver = { github = "micronaut-projects/micronaut-starter" }
url_template = "https://github.com/micronaut-projects/micronaut-starter/releases/download/v$version/micronaut-cli-$version.zip"
