name = "nats-server"
version = "2.14.5"
description = "High-Performance server for NATS.io, the cloud and edge native messaging system"
homepage = "https://github.com/nats-io/nats-server"
license = "Apache-2.0"
kind = "app"
bin = ["nats-server.exe"]

[source.x64]
url = "https://github.com/nats-io/nats-server/releases/download/v2.14.5/nats-server-v2.14.5-windows-amd64.zip"
sha256 = "f66f840a211ab665083b88e9b7edbcf6296cda143be47e53e6f6bb8520692bbb"
extract_dir = "nats-server-v2.14.5-windows-amd64"

[source.arm64]
url = "https://github.com/nats-io/nats-server/releases/download/v2.14.5/nats-server-v2.14.5-windows-arm64.zip"
sha256 = "5e1d5a5df7dc5bd9189daf25b1eb286eafc62f5659cc44996bef9294e2f4c938"
extract_dir = "nats-server-v2.14.5-windows-arm64"

[autoupdate]
checkver = { github = "nats-io/nats-server" }
url_template = { x64 = "https://github.com/nats-io/nats-server/releases/download/v$version/nats-server-v$version-windows-amd64.zip", arm64 = "https://github.com/nats-io/nats-server/releases/download/v$version/nats-server-v$version-windows-arm64.zip" }
