name = "netcoredbg"
version = "3.2.0-1092"
description = "NetCoreDbg is a managed code debugger with MI interface for CoreCLR."
homepage = "https://github.com/Samsung/netcoredbg"
license = "MIT"
kind = "app"
extract_dir = "netcoredbg"
bin = ["netcoredbg.exe"]

[source.x64]
url = "https://github.com/Samsung/netcoredbg/releases/download/3.2.0-1092/netcoredbg-win64.zip"
sha256 = "3c410a45fa502415203a94fcb88654af65bf8e3dac158a5527a722e7a6b9274a"

[autoupdate]
checkver = { github = "Samsung/netcoredbg" }
url_template = { x64 = "https://github.com/Samsung/netcoredbg/releases/download/$version/netcoredbg-win64.zip" }
