name = "arduino-cli"
version = "1.5.1"
description = "Arduino command line interface"
homepage = "https://github.com/arduino/arduino-cli"
license = "GPL-3.0-or-later"
kind = "app"
bin = ["arduino-cli.exe"]

[source.x64]
url = "https://github.com/arduino/arduino-cli/releases/download/v1.5.1/arduino-cli_1.5.1_Windows_64bit.zip"
sha256 = "fabe42e0eb04d00e776a66178299ff95a46c623dbc260f997e58fd514853dd40"

[autoupdate]
checkver = { github = "arduino/arduino-cli" }
