name = "chromedriver"
version = "153.0.8010.52"
description = "An open source tool for automated testing of webapps across many browsers"
homepage = "https://chromedriver.chromium.org/"
license = "BSD-3-Clause"
kind = "app"
extract_dir = "chromedriver-win64"
bin = ["chromedriver.exe"]

[source.x64]
url = "https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.52/win64/chromedriver-win64.zip"
sha256 = "cadc8582e8f3166040654f19c9cbc396a948990980f38dbff16522993efdf4bf"

[autoupdate]
checkver = { url = "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json", regex = "([\\d.]+)" }
url_template = { x64 = "https://storage.googleapis.com/chrome-for-testing-public/$version/win64/chromedriver-win64.zip" }
