name = "grafana"
version = "13.2.1"
description = "Open platform for analytics and data monitoring"
homepage = "https://grafana.com/"
license = "Apache-2.0"
kind = "app"
extract_dir = "grafana-13.2.1"
bin = ["bin\\grafana.exe", { name = "grafana-cli", path = "bin\\grafana.exe", args = "cli" }, { name = "grafana-server", path = "bin\\grafana.exe", args = "server -homepath \"$dir\"" }]
persist = ["conf", "data"]

[source.x64]
url = "https://dl.grafana.com/oss/release/grafana-13.2.1.windows-amd64.zip"
sha256 = "d6fdcf1af358a6492fb98e48d358abf311e9e8ee9e74f5b241bf9687b8f5c4d2"

[source.arm64]
url = "https://dl.grafana.com/oss/release/grafana-13.2.1.windows-arm64.zip"
sha256 = "84d6fd7adadedeca7010e5ae3851b4c1cb1d7cc40a06f69289af0897e3807343"

[autoupdate]
checkver = { url = "https://grafana.com/grafana/download?edition=oss&platform=windows", regex = "grafana_([\\d.]+(?:\\+security-\\d+)?)_(?<stamp>[\\d]+)_windows" }
url_template = { x64 = "https://dl.grafana.com/oss/release/grafana-$version.windows-amd64.zip", arm64 = "https://dl.grafana.com/oss/release/grafana-$version.windows-arm64.zip" }
