name = "vt-uploader"
version = "0.2.1"
description = "A simple application written in C# that allows for file uploading to the VirusTotal website. (Requires a VirusTotal API Key)"
homepage = "https://github.com/SamuelTulach/VirusTotalUploader"
license = "GPL-3.0"
kind = "app"
bin = [{ name = "vt-uploader", path = "uploader.exe" }]
shortcuts = [{ target = "uploader.exe", name = "VirusTotalUploader" }]

[source.x64]
url = "https://github.com/SamuelTulach/VirusTotalUploader/releases/download/0.2.1/vt_portable.zip"
sha256 = "77574fd3a16c1ec695a8b85fef05f813edfa8277e5f39cee38b286fc8c261419"

[autoupdate]
checkver = { github = "SamuelTulach/VirusTotalUploader" }
