name = "gram"
version = "3.3.0"
description = "A code editor for humanoid apes and grumpy toads."
homepage = "https://gram-editor.com/"
license = "GPL-3.0-or-later"
kind = "app"
extract_dir = "{code_GetInstallDir}"
bin = ["bin\\gram.exe"]
shortcuts = [{ target = "Gram.exe", name = "Gram" }]

[source.x64]
url = "https://codeberg.org/GramEditor/gram/releases/download/3.3.0/Gram-x86_64.exe"
sha256 = "05d49c8dd938b04dc72e7389c66cb7d2b2228acde3b8fff363a7de1b98402cef"
kind = "installer-archive"

[autoupdate]
checkver = "{\"jsonpath\":\"$.tag_name\",\"url\":\"https://codeberg.org/api/v1/repos/GramEditor/gram/releases/latest\"}"
url_template = { x64 = "https://codeberg.org/GramEditor/gram/releases/download/$version/Gram-x86_64.exe" }
