name = "gk"
version = "3.1.76"
description = "GitKraken CLI"
homepage = "https://www.gitkraken.com/cli"
license = "Proprietary"
kind = "app"
bin = ["gk.exe"]

[source.x64]
url = "https://github.com/gitkraken/gk-cli/releases/download/v3.1.76/gk_3.1.76_windows_amd64.zip"
sha256 = "2d607867c6b06eb690e87daf880f56f5deb8fe7a5745031d0ed1f2ad3393f91f"

[source.arm64]
url = "https://github.com/gitkraken/gk-cli/releases/download/v3.1.76/gk_3.1.76_windows_arm64.zip"
sha256 = "9b46c1c1c5d215d6862e16284d72300178141e539ba0da7bd7bd070000280ade"

[autoupdate]
checkver = { github = "gitkraken/gk-cli" }
url_template = { x64 = "https://github.com/gitkraken/gk-cli/releases/download/v$version/gk_$version_windows_amd64.zip", arm64 = "https://github.com/gitkraken/gk-cli/releases/download/v$version/gk_$version_windows_arm64.zip" }
