name = "kiro-cli"
version = "2.18.1"
description = "A CLI utility developed by Amazon that allows you to interact with Kiro's AI agents directly from your terminal."
homepage = "https://kiro.dev/cli/"
license = "Proprietary"
kind = "app"
extract_dir = "LocalApp\\Kiro-Cli"
bin = ["kiro-cli.exe"]

[source.x64]
url = "https://prod.download.cli.kiro.dev/stable/2.18.1/kiro-cli-x86_64-pc-windows-msvc.msi"
sha256 = "ea4ef225fa72cfe1d1ff147d1c0774a9af476ae9cd67469dfe0fb6e949d7ee78"
kind = "installer-archive"

[autoupdate]
checkver = "{\"jsonpath\":\"$.version\",\"url\":\"https://prod.download.cli.kiro.dev/stable/latest/manifest.json\"}"
url_template = { x64 = "https://prod.download.cli.kiro.dev/stable/$version/kiro-cli-x86_64-pc-windows-msvc.msi" }
