name = "msys2"
version = "2026-06-11"
description = "A software distro and building platform for Windows."
homepage = "http://www.msys2.org/"
license = "GPL-2.0-only|BSD-3-Clause"
kind = "app"
extract_dir = "msys64"
bin = [{ name = "msys2", path = "msys2_shell.cmd", args = "-msys2 -defterm -here -no-start" }, { name = "mingw", path = "msys2_shell.cmd", args = "-mingw -defterm -here -full-path -no-start" }, { name = "mingw32", path = "msys2_shell.cmd", args = "-mingw32 -defterm -here -full-path -no-start" }, { name = "mingw64", path = "msys2_shell.cmd", args = "-mingw64 -defterm -here -full-path -no-start" }, { name = "clang64", path = "msys2_shell.cmd", args = "-clang64 -defterm -here -full-path -no-start" }, { name = "clangarm64", path = "msys2_shell.cmd", args = "-clangarm64 -defterm -here -full-path -no-start" }, { name = "ucrt64", path = "msys2_shell.cmd", args = "-ucrt64 -defterm -here -full-path -no-start" }]
persist = ["home"]

[source.x64]
url = "https://github.com/msys2/msys2-installer/releases/download/2026-06-11/msys2-base-x86_64-20260611.tar.xz"
sha256 = "a2d047e8ee213c3c6a49a8de427eb1069df12207c0422ff1b3cbb5c905c34221"

[autoupdate]
checkver = "{\"regex\":\"/releases/tag/(?<version>(?<year>\\\\d{4})-(?<month>\\\\d{2})-(?<day>\\\\d{2}))\",\"url\":\"https://github.com/msys2/msys2-installer/releases\"}"
