name = "winsshterm"
version = "2.42.2"
description = "A tabbed SSH solution for Windows, combining PuTTY, WinSCP and VcXsrv"
homepage = "https://winsshterm.blogspot.com/"
license = "Freeware"
kind = "app"
bin = ["WinSSHTerm.exe"]
persist = ["config", "tools"]

[source.x64]
url = "https://github.com/WinSSHTerm/WinSSHTerm/releases/download/2.42.2/WinSSHTerm-2.42.2-x64.zip"
sha256 = "2dcafd19702f5c8391033f23a606493cd658e35d8c5d36ded679c63db64ca955"

[source.arm64]
url = "https://github.com/WinSSHTerm/WinSSHTerm/releases/download/2.42.2/WinSSHTerm-2.42.2-arm64.zip"
sha256 = "3e4a46b5166e44bba143d5848ee7cba684565836125982f57e9f544665b1adab"

[env]
WINSSHTERM_EXE_DISALLOW_AUTO_UPDATE = "TRUE"

[depends]
putty = "*"

[autoupdate]
checkver = { github = "WinSSHTerm/WinSSHTerm" }
