name = "codiff"
version = "1.10.1"
description = "A fast local diff viewer."
homepage = "https://github.com/nkzw-tech/codiff"
license = "MIT"
kind = "app"
extract_dir = "Codiff-win32-x64"
bin = ["codiff.exe"]
shortcuts = [{ target = "codiff.exe", name = "Codiff" }]

[source.x64]
url = "https://github.com/nkzw-tech/codiff/releases/download/v1.10.1/Codiff-win32-x64-1.10.1.zip"
sha256 = "25956048670a7c5f24e95ce329456753a9d1050448c38b6f8687f28d72245af9"

[autoupdate]
checkver = { github = "nkzw-tech/codiff" }
url_template = { x64 = "https://github.com/nkzw-tech/codiff/releases/download/v$version/Codiff-win32-x64-$version.zip" }
