name = "zulufx14-jdk"
version = "14.29.23"
description = "Open Source Builds of Zulu With OpenJFX"
homepage = "https://www.azul.com/products/zulu-community/zulufx/"
license = "GPL-2.0-only WITH Classpath-exception-2.0"
kind = "app"
extract_dir = "zulu14.29.23-ca-fx-jdk14.0.2-win_x64"

[source.x64]
url = "https://cdn.azul.com/zulu/bin/zulu14.29.23-ca-fx-jdk14.0.2-win_x64.zip"
sha256 = "e3d4755a1fb63df531d00fbaad6d77ef56acb9b5fa6a2f0540f0a95ce735ae3b"

[env]
JAVA_HOME = "{dir}"
PATH = "{dir}\\bin"

[autoupdate]
checkver = "{\"jsonpath\":\"$..download_url\",\"regex\":\"(?<name>zulu(?<version>[\\\\d.]+)-ca-fx-jdk(?<java>[\\\\d.]+)-win)_x64.zip\",\"replace\":\"${version}\",\"url\":\"https://api.azul.com/metadata/v1/zulu/packages/?java_version=14&os=windows&arch=x64&archive_type=zip&java_package_type=jdk&javafx_bundled=true&crac_supported=false&release_type=PSU&latest=true&include_fields=sha256_hash&page_size=1\"}"
