name = "qalculate"
version = "5.12.0"
description = "Multi-purpose calculator"
homepage = "https://qalculate.github.io/"
license = "GPL-2.0-or-later"
kind = "app"
extract_dir = "qalculate"
bin = ["qalc.exe", "qalculate-gtk.exe", "qalculate-qt.exe"]
shortcuts = [{ target = "qalculate-gtk.exe", name = "Qalculate! (GTK)" }, { target = "qalculate-qt.exe", name = "Qalculate! (Qt)" }]
persist = ["user"]

[source.x64]
url = "https://github.com/Qalculate/libqalculate/releases/download/v5.12.0/qalculate-5.12.0-x64.zip"
sha256 = "baf4f9612277c7e4ec5e4bdf0ff0a0487b25b5b7c159224bd910fe6f2957d4a2"

[autoupdate]
checkver = { github = "Qalculate/libqalculate" }
