name = "windows95"
version = "5.0.1"
description = "Windows 95 emulator"
homepage = "https://github.com/felixrieseberg/windows95"
license = "Freeware"
kind = "app"
shortcuts = [{ target = "windows95.exe", name = "Windows 95" }]

[source.x64]
url = "https://github.com/felixrieseberg/windows95/releases/download/v5.0.1/windows95-win32-x64-5.0.1.zip"
sha256 = "319c5a05561fe2f020540d37152be765acfc2cdcfe332b46fce7a3285956338c"

[autoupdate]
checkver = { github = "felixrieseberg/windows95" }
url_template = { x64 = "https://github.com/felixrieseberg/windows95/releases/download/v$version/windows95-win32-x64-$version.zip" }
