name = "vt-cli"
version = "1.3.1"
description = "Tool for interacting with VirusTotal"
homepage = "https://github.com/VirusTotal/vt-cli"
license = "Apache-2.0"
kind = "app"
bin = ["vt.exe"]

[source.x64]
url = "https://github.com/VirusTotal/vt-cli/releases/download/1.3.1/Windows64.zip"
sha256 = "0b355668acbd181b2b8d9a04bcf70853616fb7a96f41491243b8daaa077da947"

[autoupdate]
checkver = { github = "VirusTotal/vt-cli" }
