name = "qmplay2"
version = "26.08.02"
description = "A video and audio player which can play most formats and codecs."
homepage = "https://github.com/zaps166/QMPlay2"
license = "LGPL-3.0-only"
kind = "app"
bin = ["QMPlay2.exe"]
shortcuts = [{ target = "QMPlay2.exe", name = "QMPlay2" }]

[source.x64]
url = "https://github.com/zaps166/QMPlay2/releases/download/26.08.02/QMPlay2-Win64-26.08.02.exe#/dl.7z"
sha256 = "6e781bb5d7e0dbf9fbc122f90a0e7f718c21420531589712348fb4a17e619d59"

[autoupdate]
checkver = { github = "zaps166/QMPlay2" }
url_template = { x64 = "https://github.com/zaps166/QMPlay2/releases/download/$version/QMPlay2-Win64-$version.exe#/dl.7z" }
