name = "graalvm21-jdk17"
version = "21.3.3.1"
description = "High-performance, embeddable, polyglot Virtual Machine for JVM-langs (Java, Scala, Kotlin), JavaScript/NodeJS, Python, Ruby, R, and LLVM-langs (C, C++, Rust)"
homepage = "https://www.graalvm.org/"
license = "GPL-2.0"
kind = "app"

[source.x64]
url = "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.3.3.1/graalvm-ce-java17-windows-amd64-21.3.3.1.zip"
sha256 = "f6f6be974a69473f0caea9dca69b9c23e240408e3734e1b7f8448454237263c9"

[env]
PATH = "{dir}\\bin"
GRAALVM_HOME = "{dir}"
JAVA_HOME = "{dir}"

[autoupdate]
checkver = "{\"jsonpath\":\"$.[?(@.name =~ /^vm-21[\\\\d.]+$/)].name\",\"regex\":\"vm-([\\\\d.]+)\",\"url\":\"https://api.github.com/repos/graalvm/graalvm-ce-builds/tags?per_page=200&page=1\"}"
