name = "golangci-lint"
version = "2.12.2"
description = "Go language linters aggregator"
homepage = "https://golangci-lint.run/"
license = "GPL-3.0-only"
kind = "app"
bin = ["golangci-lint.exe"]

[source.x64]
url = "https://github.com/golangci/golangci-lint/releases/download/v2.12.2/golangci-lint-2.12.2-windows-amd64.zip"
sha256 = "bd42e3ebc8cb4ececb86941983baaf1dc221bbb04d838e94ce63b49cc91e02bb"
extract_dir = "golangci-lint-2.12.2-windows-amd64"

[source.arm64]
url = "https://github.com/golangci/golangci-lint/releases/download/v2.12.2/golangci-lint-2.12.2-windows-arm64.zip"
sha256 = "947b9a5bf762d465710b376c156f0184abb2168378b0826af1899e0ee7183742"
extract_dir = "golangci-lint-2.12.2-windows-arm64"

[autoupdate]
checkver = { github = "golangci/golangci-lint" }
url_template = { x64 = "https://github.com/golangci/golangci-lint/releases/download/v$version/golangci-lint-$version-windows-amd64.zip", arm64 = "https://github.com/golangci/golangci-lint/releases/download/v$version/golangci-lint-$version-windows-arm64.zip" }
