name = "igrep"
version = "1.3.0"
description = "Runs grep (ripgrep's library) and allows to interactively pick its results and open selected match in a text editor."
homepage = "https://github.com/konradsz/igrep"
license = "MIT"
kind = "app"
bin = ["ig.exe"]

[source.x64]
url = "https://github.com/konradsz/igrep/releases/download/v1.3.0/igrep-v1.3.0-x86_64-pc-windows-msvc.zip"
sha256 = "8ec75744a29a9eeb1a6aaaf0080b40a185420aa75884251dfd96c7c8a787ea7c"

[autoupdate]
checkver = { github = "konradsz/igrep" }
