name = "listary"
version = "7"
description = "A revolutionary search utility."
homepage = "https://www.listary.com"
license = "Shareware"
kind = "app"
shortcuts = [{ target = "Listary.exe", name = "Listary" }]

[source.x64]
url = "https://www.listary.com/download/Listary.exe?version=7#/dl.exe"
sha256 = "c62249e0d4d49bd3f062d55635cf6a3ab089ea8ee7f6c03947f6febfafaa0288"
kind = "installer-archive"

[autoupdate]
checkver = { url = "https://www.listary.com/download", regex = ">V([\\d.]+)" }
url_template = "https://www.listary.com/download/Listary.exe?version=$version#/dl.exe"
