name = "acli"
version = "1.3.22"
description = "Software to interact with Atlassian Cloud from the terminal"
homepage = "https://developer.atlassian.com/cloud/acli/"
license = "Proprietary"
kind = "app"
extract_dir = "acli_1.3.22-stable_windows_amd64"
bin = ["acli.exe"]

[source.x64]
url = "https://acli.atlassian.com/windows/1.3.22-stable/acli_1.3.22-stable_windows_amd64.zip"
sha256 = "c29484b2b4f3cd5c2aa027c030bf6f1506b7c6ae63a568d83cebee112ba00749"

[source.arm64]
url = "https://acli.atlassian.com/windows/1.3.22-stable/acli_1.3.22-stable_windows_arm64.zip"
sha256 = "7d8df822f5f00905c81ba61b36d9256c5dcb2099e23e177add7566b14d44ebe1"

[autoupdate]
checkver = { url = "https://raw.githubusercontent.com/atlassian/homebrew-acli/main/Formula/acli.rb", regex = "version \"([\\d.]+)-stable\"" }
url_template = { x64 = "https://acli.atlassian.com/windows/$version-stable/acli_$version-stable_windows_amd64.zip", arm64 = "https://acli.atlassian.com/windows/$version-stable/acli_$version-stable_windows_arm64.zip" }
