name = "z3"
version = "5.1.0"
description = "Theorem prover from Microsoft Research."
homepage = "https://github.com/Z3Prover/z3"
license = "MIT"
kind = "app"
bin = ["bin\\z3.exe"]

[source.x64]
url = "https://github.com/Z3Prover/z3/releases/download/z3-5.1.0/z3-5.1.0-x64-win.zip"
sha256 = "6ff368eaa2f9dc18acf244e736a074df877026bfc83abede6f327ebb95680535"
extract_dir = "z3-5.1.0-x64-win"

[source.arm64]
url = "https://github.com/Z3Prover/z3/releases/download/z3-5.1.0/z3-5.1.0-arm64-win.zip"
sha256 = "82a21c5526ef47df895f43734aaea163caf92ce772502235817bcfc8daadcb40"
extract_dir = "z3-5.1.0-arm64-win"

[autoupdate]
checkver = { github = "Z3Prover/z3" }
url_template = { x64 = "https://github.com/Z3Prover/z3/releases/download/z3-$version/z3-$version-x64-win.zip", arm64 = "https://github.com/Z3Prover/z3/releases/download/z3-$version/z3-$version-arm64-win.zip" }
