name = "keypirinha"
version = "2.26"
description = "A fast launcher for keyboard ninjas on Windows."
homepage = "http://keypirinha.com"
license = "Freeware"
kind = "app"
extract_dir = "Keypirinha"
bin = ["keypirinha.exe"]
shortcuts = [{ target = "keypirinha.exe", name = "Keypirinha" }]
persist = ["portable"]

[source.x64]
url = "https://github.com/Keypirinha/Keypirinha/releases/download/v2.26/keypirinha-2.26-x64-portable.7z"
sha256 = "d109a16e6a5cf311abf6d06bbe5b1be3b9ba323b79c32a168628189e10f102a5"

[autoupdate]
checkver = { github = "Keypirinha/Keypirinha" }
