name = "react-native-debugger"
version = "0.14.0"
description = "Standalone app based on official debugger of React Native, and includes React Inspector / Redux DevTools."
homepage = "https://github.com/jhen0409/react-native-debugger"
license = "MIT"
kind = "app"
shortcuts = [{ target = "react-native-debugger.exe", name = "React Native Debugger" }]

[source.x64]
url = "https://github.com/jhen0409/react-native-debugger/releases/download/v0.14.0/rn-debugger-windows-x64.zip"
sha256 = "905e87b66417def8db52503c73e3760aeaf17de14b5e11fc5bf2f010cc1f1ce3"

[autoupdate]
checkver = { github = "jhen0409/react-native-debugger" }
