name = "basilisk"
version = "2026.06.12"
description = "A XUL-based web-browser demonstrating the Unified XUL Platform (UXP). This browser is a close twin to pre-Servo Firefox in how it operates."
homepage = "https://basilisk-browser.org/"
license = "MPL-2.0"
kind = "app"
extract_dir = "basilisk"
bin = ["basilisk.exe"]
shortcuts = [{ target = "basilisk.exe", name = "Basilisk" }]

[source.x64]
url = "https://dl.basilisk-browser.org/basilisk-20260613185748.win64.7z"
sha256 = "da71cb9971da793068468f8f155c56e0fff396ca3ba7de7ed0921c1fad1ce6bf"

[autoupdate]
checkver = { url = "https://basilisk-browser.org/download.html", regex = "(?sm)https://dl.basilisk-browser.org/basilisk-(?<win32>\\d+).win32.7z.*https://dl.basilisk-browser.org/basilisk-(?<win64>\\d+).win64.7z.*basilisk-([\\d.]+)-source" }
