name = "fluxdown"
version = "0.5.4"
description = "A Rust-powered download manager with HTTP, FTP, BitTorrent and HLS/DASH streaming support."
homepage = "https://fluxdown.zerx.dev"
license = "AGPL-3.0-only"
kind = "app"
shortcuts = [{ target = "flux_down.exe", name = "FluxDown" }]
persist = ["portable_data"]

[source.x64]
url = "https://github.com/zerx-lab/FluxDown/releases/download/v0.5.4/FluxDown-0.5.4-windows-x64-portable.zip"
sha256 = "2bee9ea13553e31fae8dc19199946ef6b3fdc50b3441520de8df361aac9c1045"

[source.arm64]
url = "https://github.com/zerx-lab/FluxDown/releases/download/v0.5.4/FluxDown-0.5.4-windows-arm64-portable.zip"
sha256 = "0348e038a710dfbcc56b89b154f714cd1d067a94253200f5e5eeea55e931ad51"

[autoupdate]
checkver = { github = "zerx-lab/FluxDown" }
url_template = { x64 = "https://github.com/zerx-lab/FluxDown/releases/download/v$version/FluxDown-$version-windows-x64-portable.zip", arm64 = "https://github.com/zerx-lab/FluxDown/releases/download/v$version/FluxDown-$version-windows-arm64-portable.zip" }
