name = "netconnectchoose"
version = "1.10"
description = "Set default Internet connection and view general connection information."
homepage = "https://www.nirsoft.net/utils/net_connect_choose.html"
license = "Freeware"
kind = "app"
bin = ["NetConnectChoose.exe"]
persist = ["netconnectchoose_lng.ini", "netconnectchoose.cfg"]

[source.x64]
url = "https://www.nirsoft.net/utils/netconnectchoose.zip"
sha256 = "a2c9735688b3d763508d5b5012309604ffd365d09f3f2a99e72bc4aff906b132"

[autoupdate]
checkver = "{\"url\":\"https://www.nirsoft.net/pad/netconnectchoose.xml\",\"xpath\":\"/XML_DIZ_INFO/Program_Info/Program_Version\"}"
