name = "quarkus-cli"
version = "3.38.1"
description = "A CLI for Quarkus Java framework"
homepage = "https://quarkus.io/"
license = "Apache-2.0"
kind = "app"
extract_dir = "quarkus-cli-3.38.1"
bin = ["bin\\quarkus.bat"]

[source.x64]
url = "https://github.com/quarkusio/quarkus/releases/download/3.38.1/quarkus-cli-3.38.1.zip"
sha256 = "63b22774c6f3362a776844ad071a2b88f194104af6af52aa9d62daaeca2a05ab"

[autoupdate]
checkver = { url = "https://registry.quarkus.io/client/platforms", regex = "([\\d+\\.]+)" }
url_template = "https://github.com/quarkusio/quarkus/releases/download/$version/quarkus-cli-$version.zip"
