name = "quarkus-cli"
version = "3.39.2"
description = "A CLI for Quarkus Java framework"
homepage = "https://quarkus.io/"
license = "Apache-2.0"
kind = "app"
extract_dir = "quarkus-cli-3.39.2"
bin = ["bin\\quarkus.bat"]

[source.x64]
url = "https://github.com/quarkusio/quarkus/releases/download/3.39.2/quarkus-cli-3.39.2.zip"
sha256 = "1110161fe379d019f3309f82b78fe747c97cdc92ad16c21b0d3f26eab89c8e55"

[autoupdate]
checkver = { url = "https://registry.quarkus.io/client/platforms", regex = "([\\d+\\.]+)" }
url_template = "https://github.com/quarkusio/quarkus/releases/download/$version/quarkus-cli-$version.zip"
