name = "i2p-zero"
version = "1.20"
description = "Zero dependency, small footprint, cross-platform I2P Java Router with simple tunnel/socks controller and SAM interface"
homepage = "https://github.com/i2p-zero/i2p-zero"
license = "BSD-3-Clause|Apache-2.0"
kind = "app"
extract_dir = "i2p-zero-win.v1.20\\router"
bin = [{ name = "i2p-zero", path = "bin\\launch.bat" }]
persist = ["conf", "i2p.base"]

[source.x64]
url = "https://github.com/i2p-zero/i2p-zero/releases/download/v1.20/i2p-zero-win.v1.20.zip"
sha256 = "37c38e66a1f4935a21c2514eb4692827834ec8bd9c2dfc11d6871f7a07dbdd16"

[autoupdate]
checkver = { github = "i2p-zero/i2p-zero" }
