name = "lean-ctx"
version = "3.10.1"
description = "Context intelligence layer for AI agents."
homepage = "https://leanctx.com"
license = "Apache-2.0"
kind = "app"
bin = ["lean-ctx.exe"]

[source.x64]
url = "https://github.com/yvgude/lean-ctx/releases/download/v3.10.1/lean-ctx-x86_64-pc-windows-msvc.zip"
sha256 = "bf77386558fe8c3c6ab9967b322a45af593b99133bcfd430fee8400f88cef397"

[autoupdate]
checkver = { github = "yvgude/lean-ctx" }
url_template = { x64 = "https://github.com/yvgude/lean-ctx/releases/download/v$version/lean-ctx-x86_64-pc-windows-msvc.zip" }
