name = "httptoolkit"
version = "1.27.1"
description = "HTTP(S) debugging proxy, analyzer and client"
homepage = "https://httptoolkit.com"
license = "AGPL-3.0-or-later"
kind = "app"
shortcuts = [{ target = "HTTP Toolkit.exe", name = "HTTP Toolkit" }]

[source.x64]
url = "https://github.com/httptoolkit/httptoolkit-desktop/releases/download/v1.27.1/HttpToolkit-1.27.1-win-x64.zip"
sha256 = "a9d860d15143b602f979cfe141a33e9fc00cdcdce78787bb19df7ba217c4beee"

[autoupdate]
checkver = { github = "httptoolkit/httptoolkit-desktop" }
url_template = { x64 = "https://github.com/httptoolkit/httptoolkit-desktop/releases/download/v$version/HttpToolkit-$version-win-x64.zip" }
