name = "kiota"
version = "1.35.0"
description = "Kiota is a command line tool for generating an API client to call any OpenAPI described API you are interested in. The goal is to eliminate the need to take a dependency on a different API SDK for every API that you need to call. Kiota API clients provide a strongly typed experience with all the features you expect from a high quality API SDK, but without having to learn a new library for every HTTP API."
homepage = "https://aka.ms/kiota/docs"
license = "MIT"
kind = "app"
bin = ["kiota.exe"]

[source.x64]
url = "https://github.com/microsoft/kiota/releases/download/v1.35.0/win-x64.zip"
sha256 = "66b5547b948f7be724fa5e0ddddebda8f7b662574ae58eb9d3b8c51c609c6271"

[source.arm64]
url = "https://github.com/microsoft/kiota/releases/download/v1.35.0/win-arm64.zip"
sha256 = "b7b117c5cca14115b6581f4ecb4f5b41f1d860ee1a067a2c24287d1992bb9191"

[autoupdate]
checkver = { github = "microsoft/kiota" }
url_template = { x64 = "https://github.com/microsoft/kiota/releases/download/v$version/win-x64.zip", arm64 = "https://github.com/microsoft/kiota/releases/download/v$version/win-arm64.zip" }
