name = "zellij"
version = "0.45.1"
description = "A terminal workspace with batteries included"
homepage = "https://zellij.dev/"
license = "MIT"
kind = "app"
bin = ["zellij.exe"]

[source.x64]
url = "https://github.com/zellij-org/zellij/releases/download/v0.45.1/zellij-x86_64-pc-windows-msvc.zip"
sha256 = "b854e7b223e67d0705c5f685ef50541c38a57981b13624d09c92bed419b6f80d"

[source.linux-x64]
url = "https://github.com/zellij-org/zellij/releases/download/v0.45.1/zellij-x86_64-unknown-linux-musl.tar.gz"
sha256 = "40bcc2e03f5d5ae8e054e39f676081fe12ab70871506996ba595834c3718eefc"

[source.linux-arm64]
url = "https://github.com/zellij-org/zellij/releases/download/v0.45.1/zellij-aarch64-unknown-linux-musl.tar.gz"
sha256 = "05f0802afadd53f8db9514e7cae53c9ae8432fed1b35b8294aa816ee3044a16b"

[source.macos-x64]
url = "https://github.com/zellij-org/zellij/releases/download/v0.45.1/zellij-x86_64-apple-darwin.tar.gz"
sha256 = "8e8bea22737d1652278c51fc5c26c7c22c9855d0ebb9634a84b8873823093114"

[source.macos-arm64]
url = "https://github.com/zellij-org/zellij/releases/download/v0.45.1/zellij-aarch64-apple-darwin.tar.gz"
sha256 = "c029ba4fe1927b79ad9f0cdd59155c4dff80777863c85857d4d09b88b56f9891"

[autoupdate]
checkver = { github = "zellij-org/zellij" }
url_template = { x64 = "https://github.com/zellij-org/zellij/releases/download/v$version/zellij-x86_64-pc-windows-msvc.zip" }
