name = "jreleaser"
version = "1.26.0"
description = "Release projects quickly and easily with JReleaser"
homepage = "https://jreleaser.org"
license = "Apache-2.0"
kind = "app"
extract_dir = "jreleaser-1.26.0"
bin = ["bin\\jreleaser.bat"]

[source.x64]
url = "https://github.com/jreleaser/jreleaser/releases/download/v1.26.0/jreleaser-1.26.0.zip"
sha256 = "c821df22b1715a841024ba17c4b5233375c868e6c9dcc81612c38329c8dec628"

[autoupdate]
checkver = { github = "jreleaser/jreleaser" }
url_template = "https://github.com/jreleaser/jreleaser/releases/download/v$version/jreleaser-$version.zip"
