name = "intellij-jbr11"
version = "11_0_16-b2043.64"
description = "A fork of OpenJDK that includes a number enhancements in font rendering, HiDPI support, ligatures, performance improvements, and bugfixes. These are mainly for running IntelliJ Platform-based products"
homepage = "https://github.com/JetBrains/JetBrainsRuntime"
license = "GPL-2.0"
kind = "app"

[source.x64]
url = "https://cache-redirector.jetbrains.com/intellij-jbr/jbr_nomod-11_0_16-windows-x64-b2043.64.tar.gz"
sha256 = "c8d9bb608ab5fb5329dc6418c1074a13245d3f9f049c1034bb41a4fa0726fbc0"

[env]
PATH = "{dir}\\bin"
JAVA_HOME = "{dir}"

[autoupdate]
checkver = { github = "JetBrains/JetBrainsRuntime" }
