name = "eclipse-scout"
version = "2026-09"
description = "Eclipse IDE for Scout Developers"
homepage = "https://www.eclipse.org"
license = "EPL-1.0"
kind = "app"
extract_dir = "eclipse"
shortcuts = [{ target = "eclipse.exe", name = "Eclipse for Scout Developers" }]

[source.x64]
url = "http://download.eclipse.org/technology/epp/downloads/release/2026-09/R/eclipse-scout-2026-09-R-win32-x86_64.zip"
sha512 = "41e7254d516740c549fff1c7d3d73f763501ed4691fcc31f8b0dd720488e15c10ad9cfa440eeedcdb1368fa9e7d793429385fd321236ff7cb1c1cd7de2d3a3a0"

[autoupdate]
checkver = { url = "https://download.eclipse.org/technology/epp/downloads/release/release.xml", regex = "([\\d-]+)" }
