name = "git-xet"
version = "0.2.1"
description = "Git LFS custom transfer agent that implements upload and download of files using the Xet protocol."
homepage = "https://huggingface.co/docs/hub/xet/index"
license = "Apache-2.0"
kind = "app"
bin = ["git-xet.exe"]

[source.x64]
url = "https://github.com/huggingface/xet-core/releases/download/git-xet-v0.2.1/git-xet-windows-x86_64.zip"
sha256 = "427179c2f410bb0a1da28df590adcfbdc8fff50369f295da148fb1c9c27d2cea"

[autoupdate]
checkver = "{\"github\":\"https://api.github.com/repos/huggingface/xet-core/releases?per_page=45\",\"jsonpath\":\"$[?(@.prerelease == false)].assets[?(@.name =~ /git-xet/i)].browser_download_url\",\"regex\":\"(?i)download/git-xet-v([\\\\d.]+)/git-xet\"}"
