name = "wirelessnetconsole"
version = "1.00"
description = "View wireless networks information (console application)"
homepage = "https://www.nirsoft.net/utils/wireless_net_console.html"
license = "Freeware"
kind = "app"
bin = ["WirelessNetConsole.exe"]
persist = ["wirelessnetconsole_lng.ini", "wirelessnetconsole.cfg"]

[source.x64]
url = "https://www.nirsoft.net/utils/wirelessnetconsole.zip"
sha256 = "6b365808b7526bcfcee1cf870dd4d0602669695481ed70ed6edb2f4572abb78a"

[autoupdate]
checkver = "{\"url\":\"https://www.nirsoft.net/pad/wirelessnetconsole.xml\",\"xpath\":\"/XML_DIZ_INFO/Program_Info/Program_Version\"}"
