name = "lapce"
version = "0.4.6"
description = "Lightning-fast and Powerful Code Editor written in Rust"
homepage = "http://lapce.dev/"
license = "Apache-2.0"
kind = "app"
bin = ["lapce.exe"]
shortcuts = [{ target = "lapce.exe", name = "Lapce" }]

[source.x64]
url = "https://github.com/lapce/lapce/releases/download/v0.4.6/Lapce-windows-portable.zip"
sha256 = "23f6b30f6263cae25e933eabdfada6e50c462364a6310f671c02abd2acf1cade"

[autoupdate]
checkver = { github = "lapce/lapce" }
