name = "ktx-software"
version = "4.4.2"
description = "A collection of tools for creating/validating/supercompressing/converting or information display of ktx files."
homepage = "https://github.com/KhronosGroup/KTX-Software"
license = "Apache-2.0|Multiple licences"
kind = "app"
bin = ["bin/ktx.exe", "bin/ktx2check.exe", "bin/ktx2ktx2.exe", "bin/ktxinfo.exe", "bin/ktxsc.exe", "bin/toktx.exe"]

[source.x64]
url = "https://github.com/KhronosGroup/KTX-Software/releases/download/v4.4.2/KTX-Software-4.4.2-Windows-x64.exe#/dl.7z"
sha256 = "1f323b0fec19794f5e6c0425a61d4b1da396872a10be862d105f4f4b2d2957fe"

[source.arm64]
url = "https://github.com/KhronosGroup/KTX-Software/releases/download/v4.4.2/KTX-Software-4.4.2-Windows-arm64.exe#/dl.7z"
sha256 = "86d6edba47f3df597f3b9bceda6e4da8b4205b43c8386519e1c0d2ce804c4284"

[autoupdate]
checkver = { github = "KhronosGroup/KTX-Software" }
