name = "openssl-lts"
version = "3.0.21"
description = "TLS/SSL toolkit (3.0.X LTS)"
homepage = "https://slproweb.com/products/Win32OpenSSL.html"
license = "Apache-2.0"
kind = "app"

[source.x64]
url = "https://slproweb.com/download/Win64OpenSSL-3_0_21.exe"
sha256 = "870614d355c7c399febd863e2bdc3ae38895e9af814bbbe6ee0967622b5fbdbc"
kind = "installer-archive"

[source.arm64]
url = "https://slproweb.com/download/Win64ARMOpenSSL-3_0_21.exe"
sha256 = "041da8f2612e13692666f811169d356b356d65249c56be6e7d825a127aacc1f3"
kind = "installer-archive"

[env]
PATH = "{dir}\\bin"
OPENSSL_CONF = "{dir}\\bin\\cnf\\openssl.cnf"
OPENSSL_INCLUDE_DIR = "{dir}\\include"
OPENSSL_LIB_DIR = "{dir}\\lib"
OPENSSL_MODULES = "{dir}\\bin"

[autoupdate]
checkver = { url = "https://raw.githubusercontent.com/slproweb/opensslhashes/master/win32_openssl_hashes.json", regex = "(3\\.0\\.([\\d.]+))" }
