name = "baka-mplayer"
version = "2.0.4"
description = "FOSS libmpv based multimedia player"
homepage = "https://github.com/u8sand/Baka-MPlayer"
license = "GPL-2.0-only"
kind = "app"
shortcuts = [{ target = "Baka MPlayer.exe", name = "Baka MPlayer" }]
persist = ["bakamplayer.ini"]

[source.x64]
url = "https://github.com/u8sand/Baka-MPlayer/releases/download/v2.0.4/Baka-MPlayer.x86_64.zip"
sha256 = "c76204883caa9cf046e90fec57901871519e4c94c4cdfab2648178625f6bc4da"

[autoupdate]
checkver = { github = "u8sand/Baka-MPlayer" }
url_template = { x64 = "https://github.com/u8sand/Baka-MPlayer/releases/download/v$version/Baka-MPlayer.x86_64.zip" }
