name = "dnsproxy"
version = "0.84.1"
description = "Simple DNS proxy with DoH, DoT, DoQ and DNSCrypt support"
homepage = "https://github.com/AdguardTeam/dnsproxy"
license = "Apache-2.0"
kind = "app"
bin = ["dnsproxy.exe"]

[source.x64]
url = "https://github.com/AdguardTeam/dnsproxy/releases/download/v0.84.1/dnsproxy-windows-amd64-v0.84.1.zip"
sha256 = "83af4b4d8b185b93f7b2eb001d30eb93a659e8f5f057c085f662810a76aa87e5"
extract_dir = "windows-amd64"

[source.arm64]
url = "https://github.com/AdguardTeam/dnsproxy/releases/download/v0.84.1/dnsproxy-windows-arm64-v0.84.1.zip"
sha256 = "6613eb5030185e65ea12ab240e462ae9f36d5a929b6766257a9b467f93b690e7"
extract_dir = "windows-arm64"

[autoupdate]
checkver = { github = "AdguardTeam/dnsproxy" }
url_template = { x64 = "https://github.com/AdguardTeam/dnsproxy/releases/download/v$version/dnsproxy-windows-amd64-v$version.zip", arm64 = "https://github.com/AdguardTeam/dnsproxy/releases/download/v$version/dnsproxy-windows-arm64-v$version.zip" }
