name = "lua-language-server"
version = "3.18.2"
description = "A language server written in Lua that offers Lua language support."
homepage = "https://github.com/LuaLS/lua-language-server"
license = "MIT"
kind = "app"
bin = ["bin\\lua-language-server.exe"]
persist = ["log"]

[source.x64]
url = "https://github.com/LuaLS/lua-language-server/releases/download/3.18.2/lua-language-server-3.18.2-win32-x64.zip"
sha256 = "a4439a8f5e8e9e6505c11f045a7bf45db602124a1e246371c1dbe34924f3cf71"

[autoupdate]
checkver = { github = "LuaLS/lua-language-server" }
url_template = { x64 = "https://github.com/LuaLS/lua-language-server/releases/download/$version/lua-language-server-$version-win32-x64.zip" }
