name = "nwjs"
version = "0.113.0"
description = "An app runtime based on Chromium and NodeJS"
homepage = "https://nwjs.io"
license = "MIT"
kind = "app"
extract_dir = "nwjs-v0.113.0-win-x64"
bin = ["nwjs\\nw.exe"]

[source.x64]
url = "https://dl.nwjs.io/v0.113.0/nwjs-v0.113.0-win-x64.zip"
sha256 = "2fff537d37e827ddc0149cd3c17f5a15f71bef782d3795f7870a73b1f6cea4b1"

[autoupdate]
checkver = "{\"jsonpath\":\"$.stable\",\"regex\":\"v([\\\\d.]+)\",\"url\":\"https://nwjs.io/versions.json\"}"
