name = "warp-terminal"
version = "0.2026.09.16.08.27.stable_02"
description = "Modern, Rust-based terminal with AI built in so you and your team can build great software, faster."
homepage = "https://www.warp.dev/"
license = "Proprietary"
kind = "app"
shortcuts = [{ target = "warp.exe", name = "Warp" }]

[source.x64]
url = "https://releases.warp.dev/stable/v0.2026.09.16.08.27.stable_02/WarpSetup.exe"
sha256 = "aabff5cb57a0edb6a2bdd9369cf931e536852c7bd3c69430a0622831fa6be47b"
kind = "installer-archive"

[source.arm64]
url = "https://releases.warp.dev/stable/v0.2026.09.16.08.27.stable_02/WarpSetup-arm64.exe"
sha256 = "4a09cb4f97a88f78dc2065e9fb7661dcb7fad9a7ed7fe2e9689e593d0e719146"
kind = "installer-archive"

[autoupdate]
checkver = "{\"regex\":\"/v([\\\\d.]+stable_\\\\d+)\",\"script\":\"[System.Net.HttpWebRequest]::Create('https://app.warp.dev/download?package=exe_x86_64').GetResponse().ResponseUri.AbsoluteUri\"}"
url_template = { x64 = "https://releases.warp.dev/stable/v$version/WarpSetup.exe", arm64 = "https://releases.warp.dev/stable/v$version/WarpSetup-arm64.exe" }
